🔨 Added toolbox.sh utility script for SonarQube dev environment installation
green-code-initiative/ecoCode-java pull request #39
Opened 2024-05-05 17:41 UTC by christopherlouet

2024-05-15 18:51 UTC, dedece35 commented
Hi @christopherlouet,
PR still in progress ? or OK for review ?

2024-05-15 19:06 UTC, dedece35 requested changes
why do you move "tool_.sh" files on subdirectories ? to have a backup ? because I don't see any usage of these scripts in your toolbox.sh ... but maybe normal ?!
if it's to have a backup, OK ... but once all is ok, we have to remind to delete them and change documentation on "ecoCode-common" repository (where we explain the usage of these scripts)
warning, because, moved scripts won't success because the have to be at the root directory of the repository to succeed

2024-05-15 19:06 UTC, dedece35 commented on docker.env
> +ECOCODE_JAVA_PLUGIN_VERSION="1.6.1"
versions of postrgesql and sonarqube don't change often ... ok to manage these versions like that.
but for version plugin (here "1.6.1"), this version change very often, indeed each time we create a new release. Do you think we can find a system to get this plugin version from pom.xml, where the version is automatically managed by maven ?
second think about this plugin version, I think to be strict on version managment, I think we have to put 1.6.1-SNAPHOT here, don't you think ?

2024-05-15 19:06 UTC, dedece35 commented on toolbox.sh
> +ECOCODE_JAVA_PLUGIN_JAR="$CURRENT_PATH/target/ecocode-java-plugin-$ECOCODE_JAVA_PLUGIN_VERSION-SNAPSHOT.jar"
same feedback, I think the version will be totally managed with "SNAPSHOT" keyword included

2024-05-15 19:06 UTC, dedece35 commented on toolbox.sh
> +#!/usr/bin/env bash
WARNING ... there are some contributors on WINDOWS system, not only on Linux or MAC system.
Do you think it's ok for them ?

2024-05-15 19:06 UTC, dedece35 commented on toolbox.sh
> +function check_env() {
WARNING ... there is already a documentation and a script to check environment requirements : please check documentation here https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/starter-pack.md#method-1---automatic-check
maybe make a reference on this script (one for unix / MAc users, and one for windows users)

2024-05-15 19:07 UTC, christopherlouet commented
> Hi @christopherlouet, PR still in progress ? or OK for review ?

Hi @dedece35, the PR is still in progress. I still have to see about integrating the TOKEN and creating a release.

2024-05-15 19:14 UTC, christopherlouet commented on toolbox.sh
> +#!/usr/bin/env bash
I think it would be interesting to have a .bat script for Windows users as well.

2024-05-15 19:16 UTC, christopherlouet commented on docker.env
> +ECOCODE_JAVA_PLUGIN_VERSION="1.6.1"
I think the easiest way is to extract the version directly from the pom file.
The “SNAPHOT” prefix could be added directly to the script.

2024-05-15 19:19 UTC, christopherlouet commented
> why do you move "tool_.sh" files on subdirectories ? to have a backup ? because I don't see any usage of these scripts in your toolbox.sh ... but maybe normal ?! if it's to have a backup, OK ... but once all is ok, we have to remind to delete them and change documentation on "ecoCode-common" repository (where we explain the usage of these scripts) warning, because, moved scripts won't success because the have to be at the root directory of the repository to succeed

I'm going to add the root folder to these scripts, so that we can move these scripts into these subfolders.
If we validate this option, I'll update the “ecoCode-common” documentation.

2024-05-27 20:11 UTC, dedece35 requested changes

2024-05-27 20:11 UTC, dedece35 commented on docker.env
> +ECOCODE_DOCKERCOMPOSE_SONAR="sonarqube:10.3.0-community"
"10.5.1-community"

2024-06-29 05:07 UTC, closed without merging